version: "3"

networks:
  local_network:
    driver: bridge
    name: local_network

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    networks:
      - local_network
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb-seed:
    image: mongo:6
    container_name: mongodb-seed
    networks:
      - local_network
    depends_on:
      mongodb:
        condition: service_healthy
    links:
      - mongodb
    volumes:
      - ./service-gamification/mock_db_data/users.json:/tmp/users.json
      - ./service-gamification/mock_db_data/user-events.json:/tmp/user-events.json
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
        echo 'Adding mongo data'
        mongoimport --host=mongodb --db=pluto-main --collection=users --type=json --file=/tmp/users.json --jsonArray
        mongoimport --host=mongodb --db=pluto-main --collection=user-events --type=json --file=/tmp/user-events.json --jsonArray
        echo 'Successfully added mongo data'
      "

  api:
    image: innovation-fest-gamification-api:latest
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - local_network
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
      mongodb-seed:
        condition: service_completed_successfully

  frontend:
    image: innovation-fest-gamification-frontend:latest
    container_name: frontend
    ports:
      - "4173:4173"
