// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/badges": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "GET Badges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Badge"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Health check route",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "GET Statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.UserStatistics"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Badge": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UserStatistics": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "level_title": {
                    "type": "string"
                },
                "time_watched_ms_per_category": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_watched_ms_per_channel": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_watched_ms_per_series": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_watched_ms_total": {
                    "type": "integer"
                },
                "xp": {
                    "type": "integer"
                },
                "xp_next_level": {
                    "type": "integer"
                },
                "xp_previous_level": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
