// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/badges": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "GET Badges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Badge"
                            }
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "GET Config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.InputConfig"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Health check route",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "GET Statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserStatistics"
                        }
                    }
                }
            }
        },
        "/user_events": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "POST User Events",
                "parameters": [
                    {
                        "description": "User events data",
                        "name": "user_events",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_s-augustovitko_innovation-fest-gamification_service-gamification_src_api_models.UserEvent"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UserStatistics"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_s-augustovitko_innovation-fest-gamification_service-gamification_src_api_models.UserEvent": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "channel": {
                    "type": "string"
                },
                "episode_number": {
                    "type": "integer"
                },
                "series": {
                    "type": "string"
                },
                "time_watched_ms": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Badge": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.InputConfig": {
            "type": "object",
            "properties": {
                "update_time_ms": {
                    "type": "integer"
                }
            }
        },
        "models.UserStatistics": {
            "type": "object",
            "properties": {
                "badges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Badge"
                    }
                },
                "level": {
                    "type": "integer"
                },
                "level_title": {
                    "type": "string"
                },
                "next_level_title": {
                    "type": "string"
                },
                "previous_level_title": {
                    "type": "string"
                },
                "time_watched_ms_per_category": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_watched_ms_per_channel": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_watched_ms_per_series": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_watched_ms_total": {
                    "type": "integer"
                },
                "xp": {
                    "type": "integer"
                },
                "xp_next_level": {
                    "type": "integer"
                },
                "xp_previous_level": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
