definitions:
  github_com_s-augustovitko_innovation-fest-gamification_service-gamification_src_api_models.UserEvent:
    properties:
      category:
        type: string
      channel:
        type: string
      episode_number:
        type: integer
      series:
        type: string
      time_watched_ms:
        type: integer
      type:
        type: string
    type: object
  models.Badge:
    properties:
      name:
        type: string
    type: object
  models.InputConfig:
    properties:
      update_time_ms:
        type: integer
    type: object
  models.UserStatistics:
    properties:
      level:
        type: integer
      level_title:
        type: string
      next_level_title:
        type: string
      previous_level_title:
        type: string
      time_watched_ms_per_category:
        additionalProperties:
          type: integer
        type: object
      time_watched_ms_per_channel:
        additionalProperties:
          type: integer
        type: object
      time_watched_ms_per_series:
        additionalProperties:
          type: integer
        type: object
      time_watched_ms_total:
        type: integer
      xp:
        type: integer
      xp_next_level:
        type: integer
      xp_previous_level:
        type: integer
    type: object
info:
  contact: {}
paths:
  /badges:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Badge'
            type: array
      summary: GET Badges
  /config:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.InputConfig'
            type: array
      summary: GET Config
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check route
  /statistics:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserStatistics'
      summary: GET Statistics
  /user_event:
    post:
      consumes:
      - application/json
      parameters:
      - description: User event data
        in: body
        name: user_event
        required: true
        schema:
          $ref: '#/definitions/github_com_s-augustovitko_innovation-fest-gamification_service-gamification_src_api_models.UserEvent'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserStatistics'
      summary: POST User Event
swagger: "2.0"
